### PR TITLE
Contact Us theme updated

### PR DESCRIPTION
**Pull request by devp299**
Screenshot 2024-10-13 073617

### CODE REVIEW

**Comment by devp299** [comment]
Ok no problem. I will do it.

**Comment by devp299** [comment]
I have done with the changes in contact us form.

**Comment by neerajrathore** [comment]
@devp299 can you also add toast Controller for copy link button in share on Social Media. I can see you added that in your previous PR but not included in this one.

**Comment by devp299** [comment]
Now check everything is done. Contact us theme and updated alert.

**Review by neerajrathore — APPROVED** [review]
changes approved

**Pull request merged**
