### PR TITLE
Issue solved Go Back button 

### PR DESCRIPTION
**Pull request by devp299**

### CODE REVIEW

**Comment by devp299** [comment]
Please add hacktoberfest-accepted label

**Review by neerajrathore — COMMENTED** [review]
go back in readme is used to go back when user is viewing handbook on github! Then there we can navigate between our readme files.

**Comment by neerajrathore** [comment]
@devp299 look this [comment](https://github.com/neerajrathore/javascript-handbook/pull/91#pullrequestreview-2363806710)

**Comment by devp299** [comment]
If we are in github it will show you go back button in readme file while rendering the website it will not show that button. 
Can I do this?

**Pull request closed without merging**
