### PR TITLE
call bind apply and readme added

### PR DESCRIPTION
**Pull request by kartik3165**
Here’s a point-wise description for your open-source contribution:

---

### Title: Clarifying JavaScript Methods: `call()`, `apply()`, and `bind()`

- **Purpose**: To clarify the differences between `call()`, `apply()`, and `bind()` in JavaScript.
- **Target Audience**: Developers, especially those new to JavaScript.
- **Content Includes**:
  - Simple explanations of each method.
  - Practical code examples demonstrating usage.
  - Best practices for selecting the right method.
- **Benefits**:
  - Enhances understanding of function context.
  - Promotes better coding practices in the JavaScript community.

---

You can use or adjust these points as needed!

### CODE REVIEW

**Comment by neerajrathore** [comment]
@kartik3165 correct folder name and proper lint your code changes. Also remove your changes from root index.html

**Comment by kartik3165** [comment]
> @kartik3165 correct folder name and proper lint your code changes. Also remove your changes from root index.html

all changes done according to your request

**Comment by neerajrathore** [comment]
@kartik3165 please take latest pull from main branch to resolve conflicts.

**Comment by neerajrathore** [comment]
@kartik3165 Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your code to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!
image

**Comment by neerajrathore** [comment]
@kartik3165 closing this due to inactivity and not following basic code styles.

**Comment by kartik3165** [comment]
sorry due to my exam i am unable to follow things

**Pull request closed without merging**
