### PR TITLE
[Add] JavaScript Promises Guide

### PR DESCRIPTION
**Pull request by suryanshsingh2001**
## Description

#14 
This PR adds a comprehensive guide on **JavaScript Promises**. The guide explains the concept of promises in JavaScript, how to create them, and how to consume them with practical examples. It also covers various `Promise` API methods such as `Promise.all()`, `Promise.race()`, `Promise.any()`, and `Promise.allSettled()`.

The guide is located in a Markdown file named `Promises/README.md`.

## Changes

- Added `promises-guide.md` containing the following sections:
  - **Introduction to Promises**: Explanation of what promises are and their states.
  - **Basic Syntax**: How to create and resolve/reject promises.
  - **Consuming Promises**: Explanation of `.then()`, `.catch()`, and `.finally()`.
  - **Chaining Promises**: Example of chaining multiple promises for sequential operations.
  - **Promise API Methods**: Guide on using `Promise.all()`, `Promise.race()`, `Promise.any()`, and `Promise.allSettled()`.
  - **Error Handling in Promises**: Proper ways to handle promise rejections.

## Why this is needed

JavaScript Promises are a fundamental aspect of modern JavaScript development, especially in handling asynchronous operations. This guide will serve as a reference for developers who are new to Promises or need a refresher on their usage.

## How to Test

1. Review the`Promises/README.md` file for accuracy and clarity.
2. Confirm that the code examples run as expected in a JavaScript environment.
3. Ensure that the explanations are easy to understand for developers at all levels.

## Additional Information

- The guide also includes examples of `Promise` chaining and error handling.
- Contributions are welcome for expanding this guide in the future to cover async/await or more advanced topics related to Promises.

## Checklist

- [x] Documentation has been added.
- [x] Code examples have been tested and verified.
- [x] No breaking changes.

---

Let me know if you need more details or further modifications.

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
@neerajrathore Hey, please tag this PR as `hacktoberfest` when you merge it.

**Comment by neerajrathore** [comment]
Greetings @suryanshsingh2001!

I have tested your changes and they looks fine.

**Comment by neerajrathore** [comment]
you can add more concepts of JavaScript and help your fellow JS gang 😎

**Comment by suryanshsingh2001** [comment]
> @suryanshsingh2001 you can add more concepts of JavaScript and help your fellow JS gang 😎

Absolutely 🫡, working on it. @neerajrathore

**Pull request merged**
