### PR TITLE
Added js array methods

### PR DESCRIPTION
**Pull request by lord-cyclone100**
issue no #11 
I have added js array methods
pls check once @neerajrathore

### CODE REVIEW

**Review by neerajrathore — COMMENTED** [review]
Also add link to your Array Methods file in root README file.

**Comment by lord-cyclone100** [comment]
@neerajrathore 
done bro!!
pls check

**Review by neerajrathore — APPROVED** [review]
changes approved

**Comment by lord-cyclone100** [comment]
@neerajrathore 
pls label this as hacktoberfest-accepted

**Pull request merged**
