### PR TITLE
Added  Arrays and Loops with Todo List Project #33

### LINKED ISSUE #33: Add JavaScript Arrays and Loops Tutorial with Example Project
### Description:
I would like to contribute a section to this repository on **JavaScript Arrays and Loops**. This section will include:

#### Detailed Documentation on:
- Array properties and methods (e.g., `.push()`, `.splice()`, etc.).
- Looping mechanisms (e.g., `for`, `while`, `forEach`).
- Practical examples on how to manipulate arrays with loops.

#### Simple Project:
- A **Todo List** project to help beginners understand arrays and loops.
- Features like adding, removing, and rendering items in the list using arrays and loops.
- Interactivity such as due dates and deletion functionality.

### Request:
Could you please assign this task to me for **Hacktoberfest 2024**? I am excited to contribute to this project. @neerajrathore, please let me know if any changes are required or if I can proceed.

Looking forward to your response!

### PR DESCRIPTION
**Pull request by ajayvaniya0**
Closes #33

This PR adds a new section on JavaScript Arrays and Loops. The documentation includes:

- Detailed explanations of array properties and methods (e.g., .push(), .splice(), etc.)
- Different looping mechanisms (e.g., for, while)
- Practical examples demonstrating how to manipulate arrays with loops

Additionally, a simple Todo List project is included to help beginners understand how to use arrays and loops interactively, featuring functionalities like adding, removing, and rendering items with due dates.

### CODE REVIEW

**Comment by ajayvaniya0** [comment]
@please review it and if the changes need let me know

**Comment by ajayvaniya0** [comment]
@neerajrathore please review it and if thee changes need let me know

**Comment by ajayvaniya0** [comment]
if there no changes needed please merge it with label hacktoberfest-accpected

**Review by neerajrathore — APPROVED** [review]
changes approved

**Pull request merged**
